"""adding new fields in User model

Revision ID: 965a36ff282b
Revises: 1d7f689ccb80
Create Date: 2020-08-07 10:25:03.919854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965a36ff282b'
down_revision = '1d7f689ccb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
